title: adwm
permalink: /blog/:year/:title/
logo: /assets/images/favicon.png
url: https://murcem47.github.io

collections:
  - projects
  - webring

twitter:
  username: colepaws
  card: summary

social:
  name: colepaws
  links:
    - https://x.com/colepaws
    - https://github.com/colepaws

compress_html:
  comments: all

exclude:
  - .gitignore
  - .gitattributes
  - .prettierrc
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

markdown: kramdown
highlighter: rouge

kramdown:
  parse_block_html: false
  syntax_highlighter: rouge
  input: GFM

paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
